version: "3.7"
services:
  app:
    build:
      args:
        user: inoreds
        uid: 7777777
      context: ./
      dockerfile: Dockerfile
    image: niagahoster
    container_name: niagahoster-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - niagahoster

  db:
    image: mysql:5.7
    container_name: niagahoster-db
    restart: unless-stopped
    ports:
      - "4307:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - niagahoster

  nginx:
    image: nginx:alpine
    container_name: niagahoster-nginx
    restart: unless-stopped
    ports:
      - 8989:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - niagahoster

networks:
  niagahoster:
    driver: bridge